### PR TITLE
libticables: fix compiler error, struct usb_device missing 'struct' keyword

### PR DESCRIPTION
**Pull request by spongus711**
when building for linux, the compiler gives the following errors which have been fixed in this commit:
`
linux/link_usb.cc:402:31: error: expected primary-expression before ‘)’ token
  402 |  *udh = usb_open((usb_device *)(tigl_devices[id].dev));
`
`
linux/link_usb.cc:507:22: error: expected primary-expression before ‘)’ token
  507 |  uDev = (usb_device *)(tigl_devices[h->address].dev);
`

### CODE REVIEW

**Comment by spongus711** [comment]
I'm using Linux Mint 20.3 with libc 2.31, and libusb 1.0.0.

**Comment by debrouxl** [comment]
The libusb 1.0.x backend is in link_usb1.c, so you're compiling against the libusb 0.1.x API, whether you're using the compat layer or not.
With `libusb-1.0-0-dev` installed, try passing `--enable-libusb10` to libticables' configure explicitly. That's what both the standard libti*+gfm+tilp maintainer and the user build scripts ( https://github.com/debrouxl/tilp_and_gfm/blob/master/tilp/trunk/build/scripts/install_tilp.sh ) are doing, for historical reasons.

**Comment by adriweb** [comment]
(that said, it does look like the fix is correct? At least the other usages of this struct have `struct`)

**Comment by spongus711** [comment]
Building against libusb 0.1.12 throws the same error as before, so I think `struct` does belong there. And `--enable-libusb10` works with libusb 1.0.x, thanks.
